// examples/fastify-vue/inertia/pages/Dashboard.vue
<script setup lang="ts">
import { Link } from '@dudousxd/nestjs-inertia-client/vue';

export type ComponentProps = {
  user: { name: string };
  posts: number;
};

const props = defineProps<ComponentProps>();
</script>

<template>
  <main>
    <h1>Dashboard</h1>
    <p>Hi, {{ props.user.name }}</p>
    <p>Posts: {{ props.posts }}</p>
    <nav>
      <Link route="posts.list">View posts</Link>
    </nav>
  </main>
</template>

// examples/express-svelte/inertia/pages/Dashboard.svelte
<script lang="ts">
  import { Link } from '@dudousxd/nestjs-inertia-client/svelte';

  export type ComponentProps = {
    user: { name: string };
    items: number;
  };

  const { user, items } = $props<ComponentProps>();
</script>

<main>
  <h1>Dashboard</h1>
  <p>Hi, {user.name}</p>
  <p>Items: {items}</p>
  <nav>
    <Link route="items.list">View items</Link>
  </nav>
</main>
