// examples/express-svelte/inertia/pages/Dashboard.svelte
<script lang="ts">
  import { Link } from '@dudousxd/nestjs-inertia-client/svelte';

  export type ComponentProps = {
    user: { name: string };
    items: number;
  };

  const { user, items } = $props<ComponentProps>();
</script>

<main>
  <h1>Dashboard</h1>
  <p>Hi, {user.name}</p>
  <p>Items: {items}</p>
  <nav>
    <Link route="items.list">View items</Link>
  </nav>
</main>

// examples/express-react/inertia/pages/Dashboard.tsx
import { Link } from '@dudousxd/nestjs-inertia-client/react';

export type ComponentProps = {
  user: { id: number; name: string };
  count: number;
};

export default function Dashboard({ user, count }: ComponentProps) {
  return (
    <main>
      <h1>Dashboard</h1>
      <p>
        Hi, {user.name} ({user.id})
      </p>
      <p>Count: {count}</p>
      <nav>
        <Link route="users.list">View Users</Link>
      </nav>
    </main>
  );
}
